### ISSUE TITLE
bug/dropdownMenu

### ISSUE THREAD

**Issue by adriandarian** [UCMercedACM/ACM#11]
**Describe the bug**

Feedback form not displaying correct dropdown menu items.

**To Reproduce**
1. Go to 'Get In Touch'
2. Click on 'The third option'
3. Scroll down to 'another option and click it'

**Expected behavior**

Should change the option

**Screenshots**

![image](https://user-images.githubusercontent.com/23567187/55680484-dc0f2c80-58ce-11e9-8a41-c449b14a24a2.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 73

**Comment by GateauXD** [comment]
Fixed the bug with the dropdown menu in forms.
